POST http://localhost:3000/api/blogs Content-Type: application/json

{
    "author": "Soumya Lekkala", "title": "Sou", "url": "wemn", "likes": "7"
}

###

DELETE http://localhost:3000/api/blogs/621c304adde5225df7840bc0 Content-Type: application/json

###

PUT http://localhost:3000/api/blogs/621c32e6018fd572b17984e4 Content-Type: application/json

{
"title": "Hey there", "author": "Bullshit", "url": "6jhgd", "likes": 7
}